#ifndef LOCK_SYSTEM_HH
#define LOCK_SYSTEM_HH

#include "resolver.hh"
#include "nol.hpp"
#include "crypto_helper.hh"
#include <string>
#include <vector>
#include <fstream>
#include <iostream>
#include <filesystem>

namespace fs = std::filesystem;

class LockSystem {
public:
    static void generate_lockfile(const std::string& project_root, const std::vector<ResolvedDependency>& deps) {
        NOL::Builder builder;
        NOL::Array packages;

        for (const auto& dep : deps) {
            NOL::Object pkg;
            pkg["name"] = dep.name;
            pkg["version"] = dep.version;
            if (!dep.path.empty()) {
                pkg["path"] = dep.path;
            }

            // In a real scenario, we'd hash the actual package content
            // For now, let's hash the version and name as a placeholder if path is empty (registry package)
            if (dep.path.empty()) {
                pkg["hash"] = CryptoHelper::sha256(dep.name + "@" + dep.version);
            }

            packages.push_back(pkg);
        }

        builder.set("packages", packages);

        std::ofstream file(project_root + "/lymar.lock");
        if (!file.is_open()) {
            std::cerr << "error: could not create lymar.lock\n";
            return;
        }

        file << "# This file is automatically generated by Lyra.\n";
        file << "# It contains the exact versions and hashes of your dependencies.\n\n";
        file << builder.build().dump();
        file.close();
    }

    static bool lockfile_exists(const std::string& project_root) {
        return fs::exists(project_root + "/lymar.lock");
    }

    static std::vector<ResolvedDependency> read_lockfile(const std::string& project_root) {
        std::vector<ResolvedDependency> deps;
        std::ifstream file(project_root + "/lymar.lock");
        if (!file.is_open()) return deps;

        std::string content((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
        file.close();

        try {
            NOL::Document doc = NOL::parse(content);
            if (const auto* pkgs = doc.get("packages")) {
                if (pkgs->isArray()) {
                    for (const auto& val : pkgs->asArray()) {
                        if (val.isObject()) {
                            const auto& obj = val.asObject();
                            ResolvedDependency dep;
                            if (obj.count("name") && obj.at("name").isString()) dep.name = obj.at("name").asString();
                            if (obj.count("version") && obj.at("version").isString()) dep.version = obj.at("version").asString();
                            if (obj.count("path") && obj.at("path").isString()) dep.path = obj.at("path").asString();
                            deps.push_back(dep);
                        }
                    }
                }
            }
        } catch (const std::exception& e) {
            std::cerr << "error parsing lymar.lock: " << e.what() << std::endl;
        }

        return deps;
    }
};

#endif
