#ifndef NOLE_HH
#define NOLE_HH

#include "resolver.hh"
#include <string>
#include <vector>
#include <fstream>
#include <sstream>

class NoleWriter {
public:
    static std::string serialize(const std::vector<ResolvedDependency>& deps) {
        std::stringstream ss;
        ss << "# This file is automatically generated by Lyra.\n";
        ss << "# It contains the exact versions and paths of your dependencies.\n\n";

        for (const auto& dep : deps) {
            ss << "[[package]]\n";
            ss << "name = \"" << dep.name << "\"\n";
            ss << "version = \"" << dep.version << "\"\n";
            if (!dep.path.empty()) {
                ss << "path = \"" << dep.path << "\"\n";
            }
            ss << "\n";
        }
        return ss.str();
    }
};

class NoleDocument {
public:
    NoleDocument() = default;

    void save(const std::string& filename) {
        std::ofstream file(filename);
        if (file.is_open()) {
            file << NoleWriter::serialize(dependencies);
            file.close();
        }
    }

    std::vector<ResolvedDependency>& get_dependencies() { return dependencies; }
    const std::vector<ResolvedDependency>& get_dependencies() const { return dependencies; }

    void set_dependencies(const std::vector<ResolvedDependency>& deps) {
        dependencies = deps;
    }

private:
    std::vector<ResolvedDependency> dependencies;
};

#endif
